---
- job:
    name: rdo-mkdocs-website-build
    parent: base
    description: Build RDO mkdocs website
    run: playbooks/build.yaml
    nodeset: rdo-centos-9-stream

- job:
    name: rdo-mkdocs-website-pymarkdown
    parent: base
    description: Run markdown linter
    run: playbooks/lint_pymarkdown.yaml
    nodeset: rdo-centos-9-stream
    voting: false

- project:
    check:
      jobs:
        - rdo-mkdocs-website-build
        - rdo-mkdocs-website-pymarkdown
    gate:
      jobs:
        - rdo-mkdocs-website-build
        - rdo-mkdocs-website-pymarkdown

