site_name: An OpenStack distribution

extra_css:
  - stylesheets/extra.css

# Custom Homepage Elements
home_cover_image: assets/spencer.png # This path starts at your root mkdocs directory.s
home_tagline: RDO
home_description: |
  OpenStack, packaged for and tested on CentOS.

# Gradient Color
home_gradient_hsla: hsla(0deg,47%,55%,1) # Default Green: hsla(160deg,47%,55%,1)

# Custom Homepage Button(s)
home_button1_name: Find us!                  # Comment this parameter out to remove the button.
home_button1_url: community/                       # This path starts at your root mkdocs directory.
home_button1_theme: md-button md-button--primary # Options: "md-button", "md-button md-button--primary"
home_button1_icon: people                        # Options: "people", "gear", "image"
home_button1_blurb: |                            # Short description of this button / section.
 Check out our community and see how can you find us!

home_button2_name: Contribute  # Comment this parameter out to remove the button.
home_button2_url: contribute/    # This path starts at your root mkdocs directory.
home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button2_icon: gear       # Options: "people", "gear", "image"
home_button2_blurb: |         # Short description of this button / section.
  Looking for a way to add your package or update dependency? See our contibution documentation.

home_button3_name: Get start   # Comment this parameter out to remove the button.
home_button3_url:  contribute/onboarding/   # This path starts at your root mkdocs directory.
home_button3_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button3_icon: image      # Options: "people", "gear", "image"
home_button3_blurb: |         # Short description of this button / section.
  Documentation to help you start

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon-rdo.ico
  logo: assets/rdologo.png
  features:
      - announce.dismiss
      - content.action.edit
      - content.action.view
      - content.code.annotate
      - content.code.copy
      # - content.code.select
      # - content.footnote.tooltips
      # - content.tabs.link
      - content.tooltips
      # - header.autohide
      # - navigation.expand
      - navigation.footer
      - navigation.indexes
      # - navigation.instant
      # - navigation.instant.prefetch
      # - navigation.instant.progress
      # - navigation.prune
      - navigation.sections
      - navigation.tabs
      # - navigation.tabs.sticky
      - navigation.top
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest
      - toc.follow
      # - toc.integrate
  palette:
    scheme: rdo
nav:
  - Home: index.md
  - Deliverables:
    - deliverables/index.md
    - deliverables/release-cadence.md
    - deliverables/repos.md
    - deliverables/trunk-repos.md
    - deliverables/general_concept_comparison.md
    - deliverables/how-to-install-rdo-repo.md
  - Deploy RDO:
    - deploy/index.md
  - Contribute:
    - contribute/index.md
    - contribute/onboarding.md
    - contribute/packager.md
    - contribute/release.md
  - Process:
    - factory/index.md
    - factory/dlrn.md
    - factory/workflow-overview.md
    - factory/pipeline.md
    - factory/promotion-pipeline.md
  - Community:
    - community/index.md
    - community/faq.md
    - community/community-meeting.md

plugins:
  - redirects:
      redirect_maps:
       'repos/rdo-release.el9.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/caracal/1.el9s/noarch/rdo-release-caracal-1.el9s.noarch.rpm'
       'repos/rdo-release.el9s.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/caracal/1.el9s/noarch/rdo-release-caracal-1.el9s.noarch.rpm'
       'repos/openstack-caracal/rdo-release-caracal.el9.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/caracal/1.el9s/noarch/rdo-release-caracal-1.el9s.noarch.rpm'
       'repos/openstack-2024.1/rdo-release-2024.1.el9.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/caracal/1.el9s/noarch/rdo-release-caracal-1.el9s.noarch.rpm'
       'repos/openstack-caracal/rdo-release-caracal.el9s.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/caracal/1.el9s/noarch/rdo-release-caracal-1.el9s.noarch.rpm'
       'repos/openstack-2024.1/rdo-release-2024.1.el9s.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/caracal/1.el9s/noarch/rdo-release-caracal-1.el9s.noarch.rpm'
       'repos/openstack-bobcat/rdo-release-bobcat.el9.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/bobcat/1.el9s/noarch/rdo-release-bobcat-1.el9s.noarch.rpm'
       'repos/openstack-2023.2/rdo-release-2023.2.el9.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/bobcat/1.el9s/noarch/rdo-release-bobcat-1.el9s.noarch.rpm'
       'repos/openstack-bobcat/rdo-release-bobcat.el9s.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/bobcat/1.el9s/noarch/rdo-release-bobcat-1.el9s.noarch.rpm'
       'repos/openstack-2023.2/rdo-release-2023.2.el9s.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/bobcat/1.el9s/noarch/rdo-release-bobcat-1.el9s.noarch.rpm'
       'repos/openstack-antelope/rdo-release-antelope.el9.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/antelope/2.el9s/noarch/rdo-release-antelope-2.el9s.noarch.rpm'
       'repos/openstack-2023.1/rdo-release-2023.1.el9.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/antelope/2.el9s/noarch/rdo-release-antelope-2.el9s.noarch.rpm'
       'repos/openstack-antelope/rdo-release-antelope.el9s.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/antelope/2.el9s/noarch/rdo-release-antelope-2.el9s.noarch.rpm'
       'repos/openstack-2023.1/rdo-release-2023.1.el9s.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/antelope/2.el9s/noarch/rdo-release-antelope-2.el9s.noarch.rpm'
       'repos/openstack-zed/rdo-release-zed.el9.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/zed/2.el9s/noarch/rdo-release-zed-2.el9s.noarch.rpm'
       'repos/openstack-zed/rdo-release-zed.el9s.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/zed/2.el9s/noarch/rdo-release-zed-2.el9s.noarch.rpm'
       'repos/openstack-yoga/rdo-release-yoga.el9.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/yoga/2.el9s/noarch/rdo-release-yoga-2.el9s.noarch.rpm'
       'repos/openstack-yoga/rdo-release-yoga.el9s.rpm': 'https://cbs.centos.org/kojifiles/packages/rdo-release/yoga/2.el9s/noarch/rdo-release-yoga-2.el9s.noarch.rpm'
