- hosts: all
  tasks:
    - name: Install required packages
      become: true
      package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install mkdocs
      pip:
        name: mkdocs-material

    - name: Install mkdocs-redirect
      pip:
        name: mkdocs-redirects

    - name: Build mkdocs RDO website
      command: mkdocs build
      args:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
      register: mkdocs_exit_code

    - name: Check results of mkdocs build
      fail:
        msg: "mkdocs building failed!"
      when: mkdocs_exit_code.rc != 0

    - name: Copy static page to logs
      synchronize:
        src: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/site"
        dest: "{{ zuul.executor.log_root }}/buildset"
        mode: pull
        verify_host: true
