- hosts: all
  tasks:
    - name: Install required packages
      become: true
      package:
        name:
          - python3
          - python3-pip
        state: present

    # https://github.com/jackdewinter/pymarkdown
    - name: Install pymarkdown
      pip:
        name: pymarkdownlnt

    # Ignored rules:
    # MD013 Line length
    # MD033 Inline HTML
    - name: Run markdown linter 
      command: pymarkdown -d MD013 -d MD033 scan -r .
      args:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
